FROM ubuntu:22.04

# 设置环境变量（时区+非交互模式）
ENV DEBIAN_FRONTEND=noninteractive \
    TZ=Asia/Shanghai \
    LANG=zh_CN.UTF-8 \
    LC_ALL=zh_CN.UTF-8

# 配置阿里云镜像源并安装基础软件
RUN sed -i 's/archive.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list && \
    sed -i 's/security.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list && \
    apt-get update -y && \
    # 安装必要软件包
    apt-get install -y --no-install-recommends \
    software-properties-common\
    apt-transport-https\
    locales \
    tzdata \
    ca-certificates \
    wget \
    gnupg \
    time && \
    # 配置中文环境
    sed -i '/zh_CN.UTF-8/s/^# //g' /etc/locale.gen && \
    locale-gen zh_CN.UTF-8 && \
    # 配置时区
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone
