RUN wget https://golang.google.cn/dl/go1.24.0.linux-amd64.tar.gz
RUN tar -xvf go1.24.0.linux-amd64.tar.gz
RUN rm go1.24.0.linux-amd64.tar.gz
RUN mv go /usr/local

ENV GOROOT=/usr/local/go
ENV PATH=$GOPATH/bin:$GOROOT/bin:$PATH
ENV GOPATH=/go
ENV GOPROXY=https://mirrors.aliyun.com/goproxy/,direct

RUN apt-get install -y git
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/*


# WORKDIR /home
# RUN git clone https://github.com/ArtdragonXoX/nightcord-server.git

CMD ["/bin/bash"]